# Just the Docs Jekyll Theme Configuration
remote_theme: just-the-docs/just-the-docs

# Site settings
title: STAR Juniors
description: A list of helpful links and description for STAR members
url: "https://star-juniors.github.io"
# Color scheme
color_scheme: light

# Enable or disable the site search
search_enabled: true

# Makes Aux links open in a new tab
aux_links_new_tab: true

# External navigation links
#nav_external_links:
#  - title: GitHub Repository
#    url: https://github.com/star-juniors/star-juniors.github.io



